// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotNET_2019.Dados;

namespace dotNET_2019.Migrations
{
    [DbContext(typeof(BibliotecaDbContext))]
    [Migration("20190405181556_CreateTableLivro")]
    partial class CreateTableLivro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("dotNET_2019.Models.Livro", b =>
                {
                    b.Property<int>("LivroID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Titulo");

                    b.HasKey("LivroID");

                    b.ToTable("Livro");
                });
#pragma warning restore 612, 618
        }
    }
}
